# Generated by Django 3.2.13 on 2023-10-08 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUPA_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcv', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(65), django.core.validators.MaxValueValidator(103)])),
                ('alkphos', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(23), django.core.validators.MaxValueValidator(138)])),
                ('sgpt', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(155)])),
                ('sgot', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(82)])),
                ('gammagt', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(297)])),
                ('drinks', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('predictions', models.CharField(blank=True, max_length=200)),
                ('prediction_message', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(validators=[django.core.validators.MinValueValidator(0.08), django.core.validators.MaxValueValidator(82.0)])),
                ('hypertension', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('heart_disease', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('avg_glucose_level', models.FloatField(validators=[django.core.validators.MinValueValidator(55.12), django.core.validators.MaxValueValidator(271.74)])),
                ('bmi', models.FloatField(validators=[django.core.validators.MinValueValidator(10.3), django.core.validators.MaxValueValidator(97.6)])),
                ('gender_Male', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('gender_Other', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('work_type_Never_worked', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('work_type_Private', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('work_type_Self_employed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('work_type_children', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('Residence_type_Urban', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('smoking_status_formerly_smoked', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('smoking_status_never_smoked', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('smoking_status_smokes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stroke', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
