# Generated by Django 3.2.13 on 2023-10-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chronickidneyprediction_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronickidneyprediction',
            name='Class',
        ),
    ]
