# Generated by Django 3.2.13 on 2023-10-09 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_chronickidneyprediction_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabeticsPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_assessment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pre_screening', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ma_confidence_level_0_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(151)])),
                ('ma_confidence_level_0_6', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(132)])),
                ('ma_confidence_level_0_7', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('ma_confidence_level_0_8', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(105)])),
                ('ma_confidence_level_0_9', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(97)])),
                ('ma_confidence_level_1_0', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(89)])),
                ('exudates_confidence_level_0_5', models.FloatField(validators=[django.core.validators.MinValueValidator(0.349274), django.core.validators.MaxValueValidator(403.939108)])),
                ('exudates_confidence_level_0_6', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(167.131427)])),
                ('exudates_confidence_level_0_7', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(106.070092)])),
                ('exudates_confidence_level_0_8', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.766121)])),
                ('exudates_confidence_level_0_9', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(51.423208)])),
                ('exudates_confidence_level_1_0', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.098605)])),
                ('exudates_normalized_by_roi', models.JSONField(default=dict)),
                ('macula_optic_disc_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.367762), django.core.validators.MaxValueValidator(0.592217)])),
                ('optic_disc_diameter', models.FloatField(validators=[django.core.validators.MinValueValidator(0.057906), django.core.validators.MaxValueValidator(0.219199)])),
                ('am_fm_based_classification', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('prediction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('prediction_message', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
