# Generated by Django 3.2.13 on 2023-10-09 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diabeticsprediction_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabeticsprediction',
            name='exudates_normalized_by_roi',
        ),
        migrations.AddField(
            model_name='diabeticsprediction',
            name='exudates_normalized_by_roi_1',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.937799)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabeticsprediction',
            name='exudates_normalized_by_roi_2',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.937799)]),
            preserve_default=False,
        ),
    ]
